language: node_js
sudo: false
node_js:
  - "8"
  - "10"
env:
  global:
    - PGPORT=5433
  matrix:
    - NODE_ENV=test DEBUG=pg-sql2-fp:*
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
cache:
  directories:
    - "node_modules"
before_install:
  - export PGDATA=/home/travis/build/lfurzewaddock/pg-sql2-fp/pg_data
  - mkdir -p $PGDATA
  - initdb --locale=C -D $PGDATA
before_script:
  - npm run testBuildIntegration
  - sudo -u postgres psql -c 'CREATE DATABASE "pg-sql2-fp-ci";'
  - sudo -u postgres psql -c "CREATE USER \"pg-sql2-fp-ci\" WITH PASSWORD 'password';"
  - sudo -u postgres psql -c 'GRANT ALL PRIVILEGES ON DATABASE "pg-sql2-fp-ci" to "pg-sql2-fp-ci";'
  - sudo -u postgres psql -c 'GRANT "postgres" TO "pg-sql2-fp-ci";'
  - node -r esm test/integration/script/create-test-tables.js
script:
  - npm t
  - npm run testIntegration
after_success: npm run coveralls 