language: node_js
node_js:
  - "8"
  - "10"
env:
  - NODE_ENV=test
  - DEBUG=pg-sql2-fp:*
services:
  - postgresql
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database pg-sql2-fp-ci;' -U postgres
after_success: npm run coveralls