language: node_js
sudo: false
node_js:
  - "8"
  - "10"
env:
  global:
    - PGPORT=5433
  matrix:
    - NODE_ENV=test DEBUG=pg-sql2-fp:*
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
cache:
  directories:
    - "node_modules"
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
before_script:
  - psql -c 'CREATE DATABASE "pg-sql2-fp-ci";' -U postgres
  - node -r esm test/integration/script/create-test-tables.js
script:
  - npm t
  - npm run testIntegration
after_success: npm run coveralls