language: node_js
sudo: false
node_js:
  - "8"
  - "10"
env:
  - NODE_ENV=test DEBUG=pg-sql2-fp:*
  global:
    - PGPORT=5433
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database "pg-sql2-fp-ci";' -U postgres
  - node -r esm test/integration/script/create-test-tables.js
script:
  - npm t
  - npm run testIntegration
after_success: npm run coveralls